### ISSUE TITLE
No suitable driver found for jdbc:oracle:thin: ...

### ISSUE THREAD

**Issue by georgy** [utPLSQL/utPLSQL-maven-plugin#23]
I have a bit of a problem running utPLSQL-maven-plugin. If I simply add the plugin 

>
                      <plugin>
                        <groupId>org.utplsql</groupId>
                        <artifactId>utplsql-maven-plugin</artifactId>
                        <version>3.1.0-SNAPSHOT</version>
                        <configuration>
                             ...
                        </configuration>
                       </plugin>

Then I get following error:

> Caused by: java.lang.ClassNotFoundException: oracle.sql.ORAData

This makes me think I need to add oracle jdbc driver onto classpath of the plugin. So I added the dependencies:

>
                    <plugin>
                        <groupId>org.utplsql</groupId>
                        <artifactId>utplsql-maven-plugin</artifactId>
                        <version>3.1.0-SNAPSHOT</version>

                          <dependencies>
                            <dependency>
                              <groupId>com.oracle.jdbc</groupId>
                              <artifactId>ojdbc8</artifactId>
                              <version>12.2.0.1</version>
                            </dependency>
                            <dependency>
                              <groupId>com.oracle.jdbc</groupId>
                              <artifactId>orai18n</artifactId>
                              <version>12.2.0.1</version>
                            </dependency>
                          </dependencies>

That helps a bit, but the test run still fails with 

> Caused by: java.sql.SQLException: No suitable driver found for jdbc:oracle:thin: ...

I can't find where in the code (plugin or java-api) do you register the oracle driver class. I can see that in cli project there is Class.forName(), but nothing like it in plugin nor java-api.

What is the right way to register the driver then?

**Comment by jgarec** [comment]
Hi,

Exactly the same as #11.

I think it's related to the jdk.
JDBC Spec says that the driver should be registred automatically...

**Comment by georgy** [comment]
Which part of JDBC spec?

**Comment by georgy** [comment]
I am guessing you mean the service provider mentioned in: https://docs.oracle.com/javase/6/docs/api/java/sql/DriverManager.html

**Comment by jgarec** [comment]
Yes.

**Comment by jgarec** [comment]
I don't remember how i solved this problem on my windows computer at work.
I was not able to reproduce on my mac.

Which OS ? 
How do you get ojdbc ? from Oracle maven repository ? you install it locally ?
Which JRE ?

You're running maven through eclipse or with command line ?

**Comment by alberto-hernandez** [comment]
Hi @georgy,

All Oracle components are NOT published in the public repositories  (maven central, etc) so you need to downloaded and imported to your local maven repository. Could you check if you have it?

**Comment by georgy** [comment]
@alberto-hernandez the dependency comes from company's internal maven repo. I add the jar to the plugins classpath by adding dependency to the plugin configuration (described in my original message).

@jgarec Win 7, JDK 8, dependency comes from company's internal maven repo. I am running maven from the command line. 

I will try to debug this a bit, from looking at the source code and environment is should work.

**Comment by jgebal** [comment]
@georgy Is this issue still valid or can it be closed?

**Comment by jgebal** [comment]
Closing as no response from @georgy

**Comment by jgarec** [comment]
I reopen this issue as it's the third time someone talk about this...
But it's really hard to reproduce ...

Could you provide your pom file ? try to remove all unnecessary parts

**Comment by jgebal** [comment]
I got it working from a private repo at work (with no access to public repo).
Will provide example config and requirements.

**Comment by hinjo89** [comment]
Hi Georgy,

why did you close this again? I don't have a solution yet. How did you solve this before?

Thanks,
Johannes

**Comment by georgy** [comment]
Sorry, I was writing a comment and probably clicked close by mistake :). We ended up implementing a workaround, but as far as the issue go we don't have a solution for it. The last thing that we saw was that JDK code responsible for service discovery runs twice: first time it finds correct config file on classpath, but when it runs second time it does not find the service definition in ojdbc jar. It looks like results of the first lookup are ignored (since the driver class is not loaded), but that is all we know right now. 

This problem nags me a little bit from the back of my mind, but not enough for me to invest my time :). Not yet at least. The main complication is that the issue only reproducible on some setups and I was not able to get the repro on my environments. So the only viable solution for me is to grab a laptop from a colleague that has this issue and run away for a couple of hours. Not everyone appreciates that approach.

**Comment by pesse** [comment]
If we embed the java-api code we should make sure it's an automatic process to keep up-to-date.

Oracle driver may not be embedded or we will break license rules (there was a lengthy thread in the slack-group by Gerarld Venzl)

**Comment by hinjo89** [comment]
Hi,

sorry for the late reply, but I can't imagine that this would fix the problem, since the issue is not that the java-api and its dependencies are not on the classpath. All of them including java-api and ojdbc are on our company maven repository, so they are there.

I will try to build the referenced pull request one of these days to test it.

Thanks,
Johannes

**Comment by alesana-san** [comment]
Hey guys! It's +1 to ones who get that error.
I'm using maven to build a project so when it comes to testing it fails with `No suitable driver`. I tried the solution @jgebal described but didn't succeed. Putting driver everywhere in `pm.xml` doesn't make any difference.

**Comment by jgebal** [comment]
We probably need more info on this issue.
What version of java are you using?
What version of maven?
What is the exact stackrace?

**Comment by alesana-san** [comment]
@jgebal 

- Java: 1.8.0_45
- Maven: 3.2.5 (hash 12a6b3...)
- And for reasons unknown I can't attach here my output for `mvn clean compile liquibase:update test -P local -X > out.txt` so I put it on a slack thread.

**Comment by hinjo89** [comment]
Hi,
when I tried it last time, I tried multiple Java versions and also multiple maven versions. Always the same issue.
I gave it up after a while, but would also still be interested in case the root would be found.

**Comment by adrianhj** [comment]
Running into a similar issue.

When running liquibase-maven-plugin to set-up the database, followed by utplsql-maven-plugin to execute tests -- liquibase would run in fine and utPLSQL would crash on missing classes.

Swapping the DriverManager to DataSource as per https://github.com/adrianhj/utPLSQL-maven-plugin/commit/4a23f0c4851c2c3d290681831a503147d8a01936 seems to have resolved our issue from a quick test at least (as in it now runs liquibase maven plugin, followed by utPLSQL maven plugin OK).

**Comment by pesse** [comment]
Thank you very much, @adrianhj 
I guess we should be easily able to get rid of the DriverManager for utPLSQL doesn't really need a ConnectionPool anyway.
We plan to outsource that whole part to java-api, too, so maven-plugin and cli will be more similar.

**Comment by alesana-san** [comment]
Actually I haven't tried running tests without liquibase. Will try it as @adrianhj told

**Comment by alesana-san** [comment]
It was kinda silly of me not to try `mvn clean compile test -P profile` - it works well inside my air-gapped system. The problem really comes up when you run it like `mvn clean compile liquibase:update test ...`. Maybe it somehow messes up with drivers or something.

**Comment by jgebal** [comment]
@adrianhj - please feel free to create a PR with your updates.

**Comment by adrianhj** [comment]
I had the chance to debug a bit further today so as to understand the root cause for the Liquibase + utPLSQL combination issue.

What seems to happen is the following:

* Maven spins up a Classloader for the Liquibase Maven Plugin (see [Guide to Maven Classloading])(https://maven.apache.org/guides/mini/guide-maven-classloading.html)
* Liquibase as part of its run loads the `oracle.jdbc.driver.OracleDriver` into a child classloader it uses in [DatabaseFactory.getConnection(...)](https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/database/DatabaseFactory.java#L190,L238)
* As part of static initialisation in the `oracle.jdbc.driver.OracleDriver` it registers itself with the DriverManager
* Liquibase runs through
* The utPLSQL Maven Plugin starts up and hits [DriverManager.getConnection(...)](https://github.com/utPLSQL/utPLSQL-maven-plugin/blob/v3.1.2/src/main/java/org/utplsql/maven/plugin/UtPLSQLMojo.java#L139)
* The DriverManager sets up and starts looping through the registered drivers (containing the instance of the OracleDriver registered by the Liquibase plugin previously), it then validates whether the caller has permission to load the driver or not using [isDriverAllowed(Driver driver, ClassLoader classLoader)](https://github.com/JetBrains/jdk8u_jdk/blob/master/src/share/classes/java/sql/DriverManager.java#L661)
* The DriverManager attempts to fetch `oracle.jdbc.driver.OracleDriver` from the current utPLSQL Maven Plugin classloader, it does not yet exist so it provides a fresh one.
* `oracle.jdbc.driver.OracleDriver` runs its static initialisation logic, attempts to register itself with the DriverManager -- however as registration is `addIfAbsent` in [DriverManager.registerDriver(...)](https://github.com/JetBrains/jdk8u_jdk/blob/master/src/share/classes/java/sql/DriverManager.java#L358) the Liquibase registered one remains.
* The DriverManager validates whether the Class<OracleDriver> returned from the utPLSQL Maven Plugin classloader matches the previously registered driver -- they do not as the registered one is an instance living in the Liquibase Plugin classloader and evaluates the permission check to false
* The `DriverManager.getConnection(...)` loop continues and exhausts with no valid driver found, and subsequently raises the 'No suitable driver found for url...' exception.

I believe there are two options:

1. Retrieve and set-up an instance of the `oracle.jdbc.driver.OracleDriver` directly same as Liquibase, not going through the DriverManager.
2. Replace DriverManager with an OracleDataSource

I will open a PR for option 2 as I don't believe there is a strong need to remain DB agnostic here unless anyone believes otherwise.. :-)

**Comment by pesse** [comment]
Thanks a lot for your thorough investigation - and no, we really don't need DB agnostic approach for utPLSQL plugin ;)

**Comment by jgebal** [comment]
The issues should now be resolved by #44

**Comment by preethileela** [comment]
How does this is resolved. I am facing same issue

**Comment by alesana-san** [comment]
@preethileela have you tried the latest version of CLI? AFAIK the solution was merge into the project.

**Comment by preethileela** [comment]
It's working fine now cool

**Comment by getshravan** [comment]
when  utPLSQL-maven-plugin 3.1.3 release version made available with this [change]( https://github.com/utPLSQL/utPLSQL-maven-plugin/pull/44) ? I am still seeing 3.1.3-SNAPSHOT version

**Comment by jgebal** [comment]
Released today...
@viniciusam  - can we close this issue?
